<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:08:26.
 */
class fotoComponentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var fotoComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new fotoComponent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers fotoComponent::DrawAlbum
     * @todo   Implement testDrawAlbum().
     */
    public function testDrawAlbum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fotoComponent::DrawPicture
     * @todo   Implement testDrawPicture().
     */
    public function testDrawPicture() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fotoComponent::enableGetUrl
     * @todo   Implement testEnableGetUrl().
     */
    public function testEnableGetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fotoComponent::getUrl
     * @todo   Implement testGetUrl().
     */
    public function testGetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
