<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:08:24.
 */
class galeria_albumModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var galeria_albumModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new galeria_albumModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers galeria_albumModel::inserir
     * @todo   Implement testInserir().
     */
    public function testInserir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::editar
     * @todo   Implement testEditar().
     */
    public function testEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::apagar
     * @todo   Implement testApagar().
     */
    public function testApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::setAlbumFull
     * @todo   Implement testSetAlbumFull().
     */
    public function testSetAlbumFull() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::getEmptyAlbum
     * @todo   Implement testGetEmptyAlbum().
     */
    public function testGetEmptyAlbum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::inserirFoto
     * @todo   Implement testInserirFoto().
     */
    public function testInserirFoto() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::JoinAlbum
     * @todo   Implement testJoinAlbum().
     */
    public function testJoinAlbum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::getFotos
     * @todo   Implement testGetFotos().
     */
    public function testGetFotos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::setCapa
     * @todo   Implement testSetCapa().
     */
    public function testSetCapa() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::getCapa
     * @todo   Implement testGetCapa().
     */
    public function testGetCapa() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::albumAutentication
     * @todo   Implement testAlbumAutentication().
     */
    public function testAlbumAutentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers galeria_albumModel::getPublicAlbum
     * @todo   Implement testGetPublicAlbum().
     */
    public function testGetPublicAlbum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
