<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:08:23.
 */
class albumComponentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var albumComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new albumComponent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers albumComponent::getTemplateLinkCapa
     * @todo   Implement testGetTemplateLinkCapa().
     */
    public function testGetTemplateLinkCapa() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers albumComponent::getLinkCapa
     * @todo   Implement testGetLinkCapa().
     */
    public function testGetLinkCapa() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers albumComponent::getCapa
     * @todo   Implement testGetCapa().
     */
    public function testGetCapa() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers albumComponent::show
     * @todo   Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers albumComponent::drawAlbum
     * @todo   Implement testDrawAlbum().
     */
    public function testDrawAlbum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers albumComponent::drawCapaAlbum
     * @todo   Implement testDrawCapaAlbum().
     */
    public function testDrawCapaAlbum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers albumComponent::setUrlBasic
     * @todo   Implement testSetUrlBasic().
     */
    public function testSetUrlBasic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
